.TH "include/lr_parser.h" 3 "renderobj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/lr_parser.h \- LR parser definition\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBu_lr_action_data\fP"
.br
.ti -1c
.RI "struct \fBs_lr_action\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBt_lr_state_id\fP"
.br
.ti -1c
.RI "typedef int \fBt_lr_prod_id\fP"
.br
.ti -1c
.RI "typedef enum \fBe_lr_action_type\fP \fBt_lr_action_type\fP"
.br
.ti -1c
.RI "typedef union \fBu_lr_action_data\fP \fBt_lr_action_data\fP"
.br
.ti -1c
.RI "typedef struct \fBs_lr_action\fP \fBt_lr_action\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBe_lr_action_type\fP { \fBACTION_SHIFT\fP, \fBACTION_REDUCE\fP, \fBACTION_ERROR\fP, \fBACTION_ACCEPT\fP, \fBACTION__COUNT\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
LR parser definition\&. 


.PP
\fBAuthor\fP
.RS 4
ale-boud (ale-boud@student.42.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-29 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_lr_action\fP \fBt_lr_action\fP"

.SS "typedef union \fBu_lr_action_data\fP \fBt_lr_action_data\fP"

.SS "typedef enum \fBe_lr_action_type\fP \fBt_lr_action_type\fP"

.SS "typedef int \fBt_lr_prod_id\fP"

.SS "typedef int \fBt_lr_state_id\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBe_lr_action_type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIACTION_SHIFT \fP\fP
.TP
\fB\fIACTION_REDUCE \fP\fP
.TP
\fB\fIACTION_ERROR \fP\fP
.TP
\fB\fIACTION_ACCEPT \fP\fP
.TP
\fB\fIACTION__COUNT \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for renderobj from the source code\&.
