.TH "s_lr_stack_item" 3 "renderobj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_lr_stack_item
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lr_stack\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_lr_stack_item_type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBt_lr_stack_item_data\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBt_lr_state_id\fP \fBstate_id\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_lr_stack_item_data\fP s_lr_stack_item::data"

.SS "\fBt_lr_state_id\fP s_lr_stack_item::state_id"

.SS "\fBt_lr_stack_item_type\fP s_lr_stack_item::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for renderobj from the source code\&.
