.TH "s_lr_stack_derived" 3 "renderobj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_lr_stack_derived
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lr_stack\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_lr_prod_id\fP \fBprod_id\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* s_lr_stack_derived::data"

.SS "\fBt_lr_prod_id\fP s_lr_stack_derived::prod_id"


.SH "Author"
.PP 
Generated automatically by Doxygen for renderobj from the source code\&.
