.TH "s_token" 3 "renderobj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_token \- Describe a token\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <token\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_token_type\fP \fBtype\fP"
.br
.RI "The token type\&. "
.ti -1c
.RI "\fBt_token_data\fP \fBdata\fP"
.br
.RI "The token data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Describe a token\&. 
.SH "Field Documentation"
.PP 
.SS "\fBt_token_data\fP s_token::data"

.PP
The token data\&. 
.SS "\fBt_token_type\fP s_token::type"

.PP
The token type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for renderobj from the source code\&.
