.TH "u_lr_action_data" 3 "renderobj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_lr_action_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lr_parser\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_lr_state_id\fP \fBshift_id\fP"
.br
.ti -1c
.RI "\fBt_lr_prod_id\fP \fBreduce_id\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_lr_prod_id\fP u_lr_action_data::reduce_id"

.SS "\fBt_lr_state_id\fP u_lr_action_data::shift_id"


.SH "Author"
.PP 
Generated automatically by Doxygen for renderobj from the source code\&.
