.TH "u_lr_stack_item_data" 3 "renderobj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_lr_stack_item_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lr_stack\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_token\fP \fBtoken\fP"
.br
.ti -1c
.RI "\fBt_lr_stack_derived\fP \fBderived\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_lr_stack_derived\fP u_lr_stack_item_data::derived"

.SS "\fBt_token\fP u_lr_stack_item_data::token"


.SH "Author"
.PP 
Generated automatically by Doxygen for renderobj from the source code\&.
