.TH "u_token_data" 3 "renderobj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_token_data \- The data of token\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <token\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBword\fP"
.br
.RI "TOKEN_WORD\&. "
.ti -1c
.RI "\fBt_io_type\fP \fBio_type\fP"
.br
.RI "TOKEN_IO\&. "
.in -1c
.SH "Detailed Description"
.PP 
The data of token\&. 
.SH "Field Documentation"
.PP 
.SS "\fBt_io_type\fP u_token_data::io_type"

.PP
TOKEN_IO\&. 
.SS "char* u_token_data::word"

.PP
TOKEN_WORD\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for renderobj from the source code\&.
